export const MULTIMEDIA_SKILLS_100 = [
  // I. AI Image Generation & Creative Editing (1 - 20)
  { name: "AUTOMATIC1111/stable-diffusion-webui", desc: "Platform WebUI Stable Diffusion paling populer untuk generasi gambar lokal." },
  { name: "lllyasviel/Fooocus", desc: "Generator gambar minimalis bertenaga tinggi berbasis SDXL." },
  { name: "ComfyUI/ComfyUI", desc: "GUI Stable Diffusion berbasis diagram alir (node-based) modular." },
  { name: "stability-ai/generative-models", desc: "Repositori resmi model generatif dari Stability AI." },
  { name: "black-forest-labs/flux", desc: "Model pembuatan gambar terbaru, ultra-realistis FLUX.1." },
  { name: "lllyasviel/ControlNet", desc: "Kontrol struktur spasial presisi untuk pembuatan gambar AI." },
  { name: "apple/ml-stable-diffusion", desc: "Stable Diffusion yang dioptimalkan untuk perangkat Apple Silicon." },
  { name: "huggingface/diffusers", desc: "Pustaka Python utama untuk model difusi gambar dan video." },
  { name: "Mikubill/sd-webui-controlnet", desc: "Ekstensi ControlNet untuk Stable Diffusion WebUI." },
  { name: "haotian-liu/LLaVA", desc: "Asisten visual multimodal yang memahami isi gambar secara detail." },
  { name: "salesforce/LAVIS", desc: "Pustaka riset bahasa-visual dan analisis gambar." },
  { name: "deforum-art/deforum-stable-diffusion", desc: "Engine pembuat animasi video berbasis frame Stable Diffusion." },
  { name: "TencentARC/GFPGAN", desc: "Algoritma restorasi wajah buram/tua agar tajam dalam satu klik." },
  { name: "xinntao/Real-ESRGAN", desc: "Pengolah resolusi gambar (Super Resolution) tajam untuk foto & anime." },
  { name: "photoprism/photoprism", desc: "Sistem manajemen foto pribadi berbasis AI lokal." },
  { name: "nagadomi/waifu2x", desc: "Pustaka legendaris peningkatan resolusi gambar gaya seni/anime." },
  { name: "sberbank-ai/ru-dalle", desc: "Generator gambar berbasis arsitektur DALL-E open-source." },
  { name: "CompVis/stable-diffusion", desc: "Kode sumber asli rilis Stable Diffusion v1." },
  { name: "tanzirih/Real-ESRGAN-GUI", desc: "Antarmuka grafis ramah pengguna untuk Real-ESRGAN." },
  { name: "open-mmlab/mmgeneration", desc: "Toolkit pembuatan gambar dan video berbasis PyTorch." },

  // II. Video Generation, Editing & Video Processing (21 - 40)
  { name: "FFmpeg/FFmpeg", desc: "Engine pemrosesan, konversi, dan kompresi audio/video lintas platform." },
  { name: "obsproject/obs-studio", desc: "Software perekaman layar dan live streaming open-source populer." },
  { name: "handbrake/HandBrake", desc: "Transcoder video multi-platform untuk kompresi video tingkat lanjut." },
  { name: "GStreamer/gstreamer", desc: "Framework multimedia berbasis pipeline untuk streaming real-time." },
  { name: "mpv-player/mpv", desc: "Media player minimalis berbasis CLI dengan akselerasi GPU terbaik." },
  { name: "jellyfin/jellyfin", desc: "Server multimedia mandiri untuk streaming film dan musik pribadi." },
  { name: "openshot/openshot-qt", desc: "Editor video open-source kaya fitur ramah pengguna." },
  { name: "mltframework/mlt", desc: "Engine dan framework penyuntingan video non-linear." },
  { name: "OliveVideoEditor/olive", desc: "Editor video non-linear profesional performa tinggi." },
  { name: "xbmc/xbmc", desc: "Engine utama Kodi Media Center pengelola hiburan rumah." },
  { name: "bluenviron/mediamtx", desc: "Server media siap produksi RTSP, RTMP, WebRTC, dan HLS." },
  { name: "shengshu-ai/CogVideo", desc: "Model teks-ke-video AI open-source skala besar detail tinggi." },
  { name: "PKU-YuanGroup/Open-Sora-Plan", desc: "Proyek pembuatan replika Open-Sora untuk video sinematik." },
  { name: "HPCAitech/Open-Sora", desc: "Framework pembuatan video efisien dan beresolusi tinggi." },
  { name: "Showlab/Tune-A-Video", desc: "Generator video pendek satu langkah menggunakan Stable Diffusion." },
  { name: "bobsilverberg/video-transcoder", desc: "Aplikasi Android kompresi video lokal." },
  { name: "Kwai-VGI/LivePortrait", desc: "Teknologi animasi potret foto diam menjadi video bergerak real-time." },
  { name: "cby9890/SFML-video-player", desc: "Pemutar video terintegrasi berbasis framework SFML." },
  { name: "Nomis/webrtc-streamer", desc: "Sistem jembatan kamera RTSP ke browser menggunakan WebRTC." },
  { name: "BlueSpike/WebRTC-Express", desc: "Utilitas server instan untuk transmisi video WebRTC latensi rendah." },

  // III. Audio Synthesis, Music & Speech (TTS/STT) (41 - 60)
  { name: "coqui-ai/TTS", desc: "Pustaka sintesis suara (Text-to-Speech) untuk kloning suara natural." },
  { name: "openai/whisper", desc: "Model pengenal ucapan (Speech-to-Text) berakurasi sangat tinggi." },
  { name: "ggerganov/whisper.cpp", desc: "Porting Whisper OpenAI C/C++ cepat untuk perangkat lokal." },
  { name: "audacity/audacity", desc: "Software penyuntingan dan perekaman audio multi-track legendaris." },
  { name: "librosa/librosa", desc: "Pustaka Python utama analisis musik dan sinyal audio." },
  { name: "RVC-Project/Retrieval-based-Voice-Conversion-WebUI", desc: "Kloning suara vokal berbasis AI real-time paling populer." },
  { name: "voicepaw/so-vits-svc-fork", desc: "Fork SoftVC VITS untuk konversi vokal bernyanyi tingkat lanjut." },
  { name: "suno-ai/bark", desc: "Model pembuat audio berbasis transformer (suara, musik, efek)." },
  { name: "mumble-voip/mumble", desc: "Komunikasi suara real-time latensi rendah untuk tim game." },
  { name: "jitsi/jitsi-meet", desc: "Aplikasi konferensi video multi-platform aman." },
  { name: "navidrome/navidrome", desc: "Server streaming musik modern kompatibel protokol Subsonic." },
  { name: "beets/beets", desc: "Sistem manajemen tag perpustakaan musik otomatis bertenaga AI." },
  { name: "airsonic/airsonic", desc: "Server media berbasis Java untuk streaming audio lokal." },
  { name: "Uberi/speech_recognition", desc: "Pustaka Python pengenal suara mikrofon populer." },
  { name: "xianyi/OpenBLAS", desc: "Pustaka akselerasi CPU untuk pemrosesan sinyal audio." },
  { name: "bastibe/SoundFile", desc: "Pustaka Python performa tinggi membaca & menulis berkas suara." },
  { name: "MycroftAI/mycroft-core", desc: "Asisten suara cerdas untuk perangkat IoT dan desktop." },
  { name: "mido/mido", desc: "Pustaka Python memanipulasi data musik MIDI." },
  { name: "Spotify/pedalboard", desc: "Engine efek audio Spotify untuk gitar, vokal, dan synth." },
  { name: "deezer/spleeter", desc: "Pemasas vokal dan instrumen musik cepat bertenaga AI." },

  // IV. Computer Vision & Visual AI Analysis (61 - 80)
  { name: "opencv/opencv", desc: "Pustaka computer vision terbesar standar dunia industri." },
  { name: "ultralytics/yolov5", desc: "Engine deteksi objek real-time ikonik dan mudah dilatih." },
  { name: "ultralytics/ultralytics", desc: "Repisitori resmi YOLOv8, v9, v10 untuk deteksi & pelacakan visual." },
  { name: "pjreddie/darknet", desc: "Engine deteksi objek neural network C murni (asal mula YOLO)." },
  { name: "ageitgey/face_recognition", desc: "Toolkit pengenalan wajah sederhana akurasi tinggi." },
  { name: "tesseract-ocr/tesseract", desc: "Engine OCR pemindai teks dalam gambar legendaris." },
  { name: "jaidedai/EasyOCR", desc: "Pemindai teks gambar berbasis AI mendukung 80+ bahasa." },
  { name: "facebookresearch/segment-anything", desc: "Model Segment Anything (SAM) memotong objek visual presisi." },
  { name: "google/mediapipe", desc: "Framework pelacakan pose, wajah, tangan real-time dari Google." },
  { name: "deepinsight/insightface", desc: "Analisis wajah 2D & 3D tingkat lanjut berbasis visual AI." },
  { name: "facebookresearch/detectron2", desc: "Sistem deteksi & segmentasi objek mutakhir Meta AI." },
  { name: "open-mmlab/mmdetection", desc: "Toolkit deteksi objek modular berbasis PyTorch." },
  { name: "open-mmlab/mmpose", desc: "Toolkit pelacakan sendi tubuh (pose estimation) performa tinggi." },
  { name: "open-mmlab/mmocr", desc: "Toolkit OCR modern deteksi teks liar di jalanan." },
  { name: "dlib/dlib", desc: "Algoritma C++ machine learning pengenalan wajah & landmark." },
  { name: "scikit-image/scikit-image", desc: "Algoritma pemrosesan gambar ilmiah untuk Python." },
  { name: "Kornia/kornia", desc: "Pustaka computer vision berbasis tensor diferensial PyTorch." },
  { name: "albumentations-team/albumentations", desc: "Pustaka augmentasi gambar cepat melatih model AI." },
  { name: "microsoft/computervision-recipes", desc: "Kumpulan praktik terbaik visi komputer Microsoft." },
  { name: "intel-isl/Open3D", desc: "Pustaka modern pengolahan data visual 3D (point cloud)." },

  // V. 3D Rendering, Graphics, WebVR & VFX Engines (81 - 100)
  { name: "blender/blender", desc: "Software pembuat konten 3D, animasi, modeling, dan VFX terhebat." },
  { name: "godotengine/godot", desc: "Game engine grafis 2D & 3D open-source sangat ringan & bertenaga." },
  { name: "mrdoob/three.js", desc: "Pustaka JS terpopuler render grafis 3D interaktif di browser." },
  { name: "babylonjs/Babylon.js", desc: "Web 3D engine industri kaya fitur performa tinggi." },
  { name: "pixijs/pixijs", desc: "Engine render grafis 2D HTML5 cepat dengan WebGL." },
  { name: "playcanvas/engine", desc: "WebGL game engine berbasis cloud dioptimalkan untuk seluler." },
  { name: "cocos/cocos-engine", desc: "Engine grafis game multi-platform pembuatan game mobile." },
  { name: "libgdx/libgdx", desc: "Framework Java lintas platform pembuatan game performa tinggi." },
  { name: "OgreCave/ogre", desc: "Engine rendering grafis 3D C++ kelas berat legendaris." },
  { name: "openscenegraph/OpenSceneGraph", desc: "Toolkit visualisasi 3D militer, simulasi, dan game." },
  { name: "PixarAnimationStudios/OpenSubdiv", desc: "Teknologi subdivisi permukaan 3D Pixar." },
  { name: "AcademySoftwareFoundation/openvdb", desc: "Standar industri VFX untuk simulasi volumetrik (asap, api)." },
  { name: "mitsuba-renderer/mitsuba3", desc: "Sistem rendering berbasis fisika untuk riset visual." },
  { name: "Embree/embree", desc: "Koleksi kernel ray-tracing kinerja tinggi dari Intel." },
  { name: "IntelRealSense/librealsense", desc: "SDK resmi integrasi sensor kamera kedalaman 3D RealSense." },
  { name: "webrender/webrender", desc: "Engine rendering halaman web berbasis GPU dari Mozilla." },
  { name: "CesiumGS/cesium", desc: "Visualisasi bumi 3D dan peta geospasial interaktif." },
  { name: "unrealcv/unrealcv", desc: "Jembatan visi komputer mengekstrak data dari Unreal Engine." },
  { name: "ssloy/tinyrenderer", desc: "Rekonstruksi software renderer 3D 500 baris kode C++." },
  { name: "gargaj/bonzomatic", desc: "Alat live-coding shader grafis GLSL untuk kompetisi VFX." }
];
