const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');

const compositeApi = `
  // Composite Image API Route (Face + Clothes + Background Seamless Fusion)
  app.post("/api/composite-image", async (req, res) => {
    try {
      const { faceUrl, clothesUrl, backgroundUrl, userPrompt, aspectRatio = "1:1" } = req.body;
      const cleanUserPrompt = userPrompt || "A realistic, elegant fashion portrait";
      
      const composedPrompt = \`Ultra-Photorealistic Composition: A real human with identical facial structure and expressions matching the face reference, wearing the outfit matching the clothing reference, placed naturally within the background scene. \${cleanUserPrompt}. Amateur smartphone candid photo, visible pores, asymmetric features, harsh natural lighting, messy real-world background. ZERO plastic skin, zero doll face, zero CGI.\`;

      const parts = [];
      
      const parseDataUrl = (dataUrl) => {
        if (!dataUrl || !dataUrl.startsWith("data:")) return null;
        const match = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
        if (!match) return null;
        return { mimeType: match[1], base64: match[2] };
      };

      if (faceUrl && faceUrl.startsWith('data:')) {
        const parsed = parseDataUrl(faceUrl);
        if (parsed) parts.push({ inlineData: { mimeType: parsed.mimeType, data: parsed.base64 } });
      }
      if (clothesUrl && clothesUrl.startsWith('data:')) {
        const parsed = parseDataUrl(clothesUrl);
        if (parsed) parts.push({ inlineData: { mimeType: parsed.mimeType, data: parsed.base64 } });
      }
      if (backgroundUrl && backgroundUrl.startsWith('data:')) {
        const parsed = parseDataUrl(backgroundUrl);
        if (parsed) parts.push({ inlineData: { mimeType: parsed.mimeType, data: parsed.base64 } });
      }
      parts.push({ text: composedPrompt });

      const response = await serverKeyRotator.executeWithRotation(req, async (aiClient) => {
        return await aiClient.models.generateContent({
          model: 'gemini-3.1-flash-image',
          contents: { parts },
          config: {
            outputMimeType: 'image/jpeg',
            aspectRatio: (["1:1", "16:9", "9:16", "4:3", "3:4"].includes(aspectRatio) ? aspectRatio : "1:1"),
            personGeneration: 'allow_all'
          }
        });
      });

      let base64Image = null;
      let mimeType = 'image/png';
      
      if (response?.text) {
          base64Image = response.text; // Assuming base64 is returned as text for image models in SDK
          mimeType = 'image/jpeg';
      }

      if (base64Image) {
        return res.json({ success: true, imageBase64: \`data:\${mimeType};base64,\${base64Image}\`, composedPrompt });
      }
      throw new Error("No image generated by Gemini");
    } catch (e) {
      console.error("Composite Engine Error:", e);
      res.status(500).json({ success: false, error: String(e) });
    }
  });
`;

const targetIndex = code.indexOf('if (process.env.NODE_ENV !== "production") {');
if (targetIndex !== -1) {
    code = code.substring(0, targetIndex) + compositeApi + '\n  ' + code.substring(targetIndex);
    fs.writeFileSync('server.ts', code);
    console.log('Successfully added /api/composite-image');
} else {
    console.log('Could not find injection point');
}
